import MenuHeader from "@/component/menu/MenuHeader";
import "./globals.css";
export const metadata = {
  title: "Next Authen",
  description: "Generated by create next app",
};
import "bootstrap/dist/css/bootstrap.min.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuHeader />
        {children}
      </body>
    </html>
  );
}
