export const metadata = {
  title: "NextAuth",
  description: "Generated by create next app",
};
import MenuHeader from "@/component/menu/MenuHeader";
import "./globals.css";
import "./style.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuHeader />
        {children}
      </body>
    </html>
  );
}
