import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const link = {
  rel: "stylesheet",
  href: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css",
};
import "./style.css";
import { Providers } from "./providers";
import Header from "@/components/header/Header";
import FooterPage from "@/components/footer/Footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel={link.rel} href={link.href} />
      </head>
      <Providers>
        <body>
          <Header />
          {children}
          <FooterPage />
        </body>
      </Providers>
    </html>
  );
}
